services:
  db:
    container_name: mysql
    image: mysql
    env_file:
      - .env
    ports:
      - 3306:3306

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bubblemap
    depends_on:
      - db
    ports:
      - 3003:3003
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
